### ISSUE TITLE
ebuf wrapping unrelated error

### ISSUE THREAD

**Issue by WindzCUHK** [yahoojapan/athenz-authorizer#18]
https://github.com/yahoojapan/athenz-authorizer/blob/62bbcd58c2a7ddf31bf272de3f117b56974c4516/jwk/daemon.go#L82-L86

`ebuf` wrapping unrelated error

**Comment by kevindiu** [comment]
fixed?

**Comment by WindzCUHK** [comment]
the code is still there
https://github.com/yahoojapan/athenz-authorizer/blob/master/jwk/daemon.go#L76-L96

**Comment by WindzCUHK** [comment]
continued in: https://github.com/AthenZ/athenz-authorizer/issues/2
