### ISSUE TITLE
Policy Expired Hook, empty policy time gap

### ISSUE THREAD

**Issue by WindzCUHK** [yahoojapan/athenz-authorizer#28]
https://github.com/yahoojapan/athenz-authorizer/blob/b56348ee1371d14e26ce2af5e4cc5226f548ea7d/policy/daemon.go#L173-L176

# issue
1. ExpiredHook is called after the policy is deleted from the cache, checking policy before fetch success will be same as checking empty policy.
2. There is no retry or error handling inside the hook.
3. If we need to rely on the periodical `Update()` call to keep the policy valid anyway, we don't need this logic here.

**Comment by WindzCUHK** [comment]
currently, the policy will keep on updating, the expire hook will not run at all.

**Comment by kevindiu** [comment]
policy cache should not depends about the expired hook, it should depends on the refresh mechanism.
expired hook is just for safety.

**Comment by WindzCUHK** [comment]
we should not assume policy will not expire...
no solutions yet, just keep this open

**Comment by kevindiu** [comment]
I did not assume policy will not expire.... policy expiration is depends on Athenz server, we need to set it correctly anyway. I think user need to pay attention on policy refresh duration otherwise the policy cache maybe insecure enough for their use.

**Comment by WindzCUHK** [comment]
We even the expire hook runs, this will be a problem.
The user can only set the refresh duration, so that the expire hook never runs.

**Comment by kevindiu** [comment]
So it will keep retrying to refresh policy anyway. 
Actually I want to get rid of expire hook and it makes no sense for me.

**Comment by WindzCUHK** [comment]
continue in: https://github.com/AthenZ/athenz-authorizer/issues/3
