### ISSUE TITLE
fix inconsistent configuration naming

### ISSUE THREAD

**Issue by WindzCUHK** [yahoojapan/athenz-authorizer#37]
1. `WithPolicyExpiredDuration` is missing in `authorizerd.go`
1. https://github.com/yahoojapan/athenz-authorizer/blob/master/option.go
    1. `WithPolicyExpireMargin` => `WithPolicyExpireMarginDur`
    1. `WithPolicyExpiredDuration` => `WithPolicyFlushDur`
    1. `WithPolicyEtagFlushDur` => `WithPolicyEtagFlushDur`
    1. `WithPolicyErrRetryInterval` => `WithPolicyErrRetryDur`
    1. `WithPolicyRefreshDuration` => `WithPolicyRefreshDur`

**Comment by kevindiu** [comment]
fixed and close :)
