### ISSUE TITLE
role policy cache swap is not atomic

### ISSUE THREAD

**Issue by WindzCUHK** [yahoojapan/athenz-authorizer#47]
1. swap logic is not atomic, better use `atomic.SwapPointer()`
https://github.com/yahoojapan/athenz-authorizer/blob/21878194b751a3ee169334cc8a4b305025597eeb/policy/daemon.go#L179
2. [fixed in #49] policy pointer may be changed during checking, should cache the pointer variable to local
(add unit test later)
https://github.com/yahoojapan/athenz-authorizer/blob/21878194b751a3ee169334cc8a4b305025597eeb/policy/daemon.go#L206

**Comment by kevindiu** [comment]
1. I think it is atomic operation... I am searching for it.
2. I think for now the function use this variable once, so we do not need to cache it. Also this logic will change in near future, so we do not need to touch this code for now.

**Comment by kevindiu** [comment]
1. In this case atomic or not is not important...

**Comment by kevindiu** [comment]
I think we do not need to work on this issue, so I will close it

**Comment by WindzCUHK** [comment]
1. calling `Update()` concurrently, writes to `p.rolePolicies` is racing
2. `CheckPolicy()` will be wrong, if swap happen in the middle

**Comment by kevindiu** [comment]
1. if will not happen as p.rolePolicies will keep the most updated policy, we don't care about the old policy object
2. same as 1, the main point is assign the new `rp` map to `p.rolePolicies`

**Comment by WindzCUHK** [comment]
1. we need to stop the `rp` after the swap
https://github.com/yahoojapan/athenz-authorizer/blob/21878194b751a3ee169334cc8a4b305025597eeb/policy/daemon.go#L179-L181
init state: `p.cache = oldCache`
Update 1:
p.cache = newRp1
rp1 = oldCache
Update 2:
p.cache = newRp2
rp2 = oldCache/newRp1 (racing)

if rp2=newRp1, its expire go routine will not end and leaked

2. fixed in https://github.com/yahoojapan/athenz-authorizer/pull/49

**Comment by kevindiu** [comment]
Can you confirm if 
```
 p.rolePolicies, rp = rp, p.rolePolicies 
``` 
is atomic instruction or not? 
I am not sure about it.
