### ISSUE TITLE
refactor role package

### ISSUE THREAD

**Issue by kyfujisa** [yahoojapan/athenz-authorizer#60]
The access token feature added in this PR #56 is implemented in the role package.
It should be divided into access packages.

**Comment by kyfujisa** [comment]
I think it would be good to match this to atpParams.
https://github.com/yahoojapan/athenz-authorizer/blob/930b45d7acc36c92377872b0f6597ff6d7c15c98/role/processor.go#L45-L49
https://github.com/yahoojapan/athenz-authorizer/blob/930b45d7acc36c92377872b0f6597ff6d7c15c98/option.go#L44-L47

**Comment by WindzCUHK** [comment]
TODO: add test cases for `*Verifier :=` wrapper functions in `func (a *authorizer) initVerifiers() error`

**Comment by WindzCUHK** [comment]
continue in: https://github.com/AthenZ/athenz-authorizer/issues/5
