### ISSUE TITLE
[role certificate] Role in CN is not extracted

### ISSUE THREAD

**Issue by WindzCUHK** [yahoojapan/athenz-authorizer#82]
# Suggestion

Also extract role from role certificate in the CN field.

# Details

Other than roles in the SAN field, Athenz also consider roles in the CN field as valid role.
https://github.com/yahoo/athenz/blob/59420f467bb683b6ac032e49d68a21777734c192/libs/java/auth_core/src/main/java/com/yahoo/athenz/auth/impl/CertificateIdentityParser.java#L107

The current implementation only extract roles from the SAN field.
https://github.com/yahoojapan/athenz-authorizer/blob/00230677f41c8a1b2bb49f184397972772e12f7a/authorizerd.go#L475-L488

**Comment by kanosaki** [comment]
I gonna try to fix this issue, is that ok?
