### ISSUE TITLE
logging library glg causes data race detection

### ISSUE THREAD

**Issue by JunTakagi** [yahoojapan/athenz-authorizer#99]
Athenz-authorizer uses library glg for logging, and this library uses fastime.
Because fastime's init function create groutine which calls `time.Now()` periodically, if another thread (maybe main thread of  athenz-authorizer user) tries to set `time.Local`, data race is detected by go test with `-race` option.
I think using glg is not the best way, so please think about anohter logging library.

**Comment by WindzCUHK** [comment]
@JunTakagi 

Are you setting the `time.Local` directly like below?
```go
loc, err := time.LoadLocation("Asia/Tokyo")
time.Local = loc
```

Can you try to set timezone like below before the `time` package is imported?
```
os.Setenv("TZ", "Asia/Tokyo")
```

@kpango
Do you have other idea for changing the timezone in `glg`/`fastime`?

**Comment by kpango** [comment]
It's okay using another logging libs!!

**Comment by JunTakagi** [comment]
@WindzCUHK 
Yes, I have set `time.Local` directly.
As you pointed out, I fixed my code to set `TZ` instead of `time.Local` then it works well and no data race now.
I close this issue, thank you so match!!
